name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy_gcs:
    name: deploy functions
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_VAR_trello_token: ${{ secrets.TRELLO_TOKEN }}
      TF_VAR_trello_key: ${{ secrets.TRELLO_KEY }}
      TF_VAR_trello_list_shopping: ${{ secrets.TRELLO_LIST_SHOPPING }}
      TF_VAR_trello_list_todo: ${{ secrets.TRELLO_LIST_TODO }}
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: add release tag
        id: add_release_version
        uses: anothrNick/github-tag-action@master

      - name: Setup Google Cloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '275.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: upload to gcs
        run: |
          zip -r src_${{ steps.add_release_version.outputs.tag }}.zip .
          gsutil mv src_${{ steps.add_release_version.outputs.tag }}.zip ${{ secrets.GCS_BUCKET }}
        working-directory: ./src/

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
            tf_actions_version: 0.12.20
            tf_actions_subcommand: 'init'
            tf_actions_working_dir: 'infra'
        env:
            TF_VAR_release_version: ${{ steps.add_release_version.outputs.tag }}
            TF_VAR_service_account_key: ${{ secrets.GCP_SA_KEY }}
            GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY_ }}

      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
            tf_actions_version: 0.12.20
            tf_actions_subcommand: 'validate'
            tf_actions_working_dir: 'infra'
        env:
            TF_VAR_release_version: ${{ steps.add_release_version.outputs.tag }}
            TF_VAR_service_account_key: ${{ secrets.GCP_SA_KEY }}
            GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY_ }}

      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
            tf_actions_version: 0.12.20
            tf_actions_subcommand: 'plan'
            tf_actions_working_dir: 'infra'
        env:
            TF_VAR_release_version: ${{ steps.add_release_version.outputs.tag }}
            TF_VAR_service_account_key: ${{ secrets.GCP_SA_KEY }}
            GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY_ }}

      - name: 'Terraform Apply'
        uses: hashicorp/terraform-github-actions@master
        with:
            tf_actions_version: 0.12.20
            tf_actions_subcommand: 'apply'
            tf_actions_working_dir: 'infra'
        env:
            TF_VAR_release_version: ${{ steps.add_release_version.outputs.tag }}
            TF_VAR_service_account_key: ${{ secrets.GCP_SA_KEY }}
            GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY_ }}

